### ISSUE TITLE
[Q] How to detect end of rtmp stream?

### ISSUE THREAD

**Issue by hnvn** [ant-media/ExoPlayer-with-RTMP-and-FLV-seek#3]
I've tried playing a rtmp stream from Wowza Server, it works well. But, when I finish the stream, how can I detect that state in client side? I try to check the state of Exoplayer , but it jumps to ExoPlayer.STATE_BUFFERING, not ExoPlayer.STATE_ENDED.

**Comment by mekya** [comment]
Hi @hnvn , we published a new version for the rtmp client library which is ready to use at this repo https://github.com/ant-media/LiveVideoBroadcaster

In this new version, state ended event is fired and you can understand the end of rtmp stream. 

For this repo, we will publish a new version for rtmp client library which has a smaller sdk level and update this repo soon. 

By the way, we develop media server which is powerful version of red5. It has adaptive streaming, mp4, hls muxing, rtsp, webrtc, etc.  In addition, it is much more cost-effective than other solutions. 
I think you may want to try it and you can ask me anything about it ;)

http://antmedia.io

**Comment by hnvn** [comment]
Thanks for quick response. I'll try upgrading rtmp client library.

**Comment by mekya** [comment]
With the current commit you should detect the end of the stream.
