### ISSUE TITLE
Exoplayer not playing link 

### ISSUE THREAD

**Issue by DemindoO** [ant-media/ExoPlayer-with-RTMP-and-FLV-seek#4]
I tried to this link in this sample it's not work but its play video in vlc
here is link of rtmp  video
rtmp://pkpipe.com:1935/vod/\_definst\_/test/1.mp4

**Comment by mekya** [comment]
@DemindoO I catched you. Same question and same answer;)

Please try this way 
"rtmp://202.125.150.108:1935/vod/_definst_/test/1.mp4 app=vod playpath=test/1.mp4"

Please let me know if it works

**Comment by DemindoO** [comment]
Thanks so much  brother for replying  it work :) if url does not have any space .if it has any space it stop working (Exception connection to server is lost ) (but it work in vlc ) .

this url does not work
rtmp://pkpipe.com:1935/vod2/\_definst\_/pkpipe/Bya6kPBOZ/Top Ten Most Beautiful Places in Pakistan _ The Pioneers Presentation.mp4 app=vod2 playpath=/pkpipe/Bya6kPBOZ/Top Ten Most Beautiful Places in Pakistan _ The Pioneers Presentation.mp4

**Comment by mekya** [comment]
Replace space characters with \20 and try again

Here is the url working for me

rtmp://pkpipe.com:1935/vod2/_definst_/pkpipe/Bya6kPBOZ/Top\20Ten\20Most\20Beautiful\20Places\20in\20Pakistan\20_\20The\20Pioneers\20Presentation.mp4 app=vod2 playpath=pkpipe/Bya6kPBOZ/Top\20Ten\20Most\20Beautiful\20Places\20in\20Pakistan\20_\20The\20Pioneers\20Presentation.mp4
